[system]
port = "1112"
mode = "debug"
quit_max_time = 5

[zap]

[lumberjack]

[storage]
  [storage.mysql]
  ip = "192.168.181.90"
  port = "3306"
  user = "root"
  password = "123456"
  database = "xl"

  [storage.redis]

